### PR TITLE
Ensure all files are read as utf-8

### LINKED ISSUE #4: External encoding of files should be defined in code
Running ```LANG=C rspec spec``` results in failures such as:

```
 21) I18nData using I18nData::FileDataProvider .countries translated has default for languages that only have subtypes
     Failure/Error: I18nData.countries('ZH')['DK'].should == '丹麦'
     ArgumentError:
       invalid byte sequence in US-ASCII
     # /builddir/build/BUILD/rubygem-i18n_data-0.4.0/usr/share/gems/gems/i18n_data-0.4.0/lib/i18n_data/file_data_provider.rb:32:in `split'
     # /builddir/build/BUILD/rubygem-i18n_data-0.4.0/usr/share/gems/gems/i18n_data-0.4.0/lib/i18n_data/file_data_provider.rb:32:in `block in read_from_file'
     # /builddir/build/BUILD/rubygem-i18n_data-0.4.0/usr/share/gems/gems/i18n_data-0.4.0/lib/i18n_data/file_data_provider.rb:31:in `each'
     # /builddir/build/BUILD/rubygem-i18n_data-0.4.0/usr/share/gems/gems/i18n_data-0.4.0/lib/i18n_data/file_data_provider.rb:31:in `read_from_file'
     # /builddir/build/BUILD/rubygem-i18n_data-0.4.0/usr/share/gems/gems/i18n_data-0.4.0/lib/i18n_data/file_data_provider.rb:7:in `codes'
     # /builddir/build/BUILD/rubygem-i18n_data-0.4.0/usr/share/gems/gems/i18n_data-0.4.0/lib/i18n_data.rb:19:in `block in countries'
     # /builddir/build/BUILD/rubygem-i18n_data-0.4.0/usr/share/gems/gems/i18n_data-0.4.0/lib/i18n_data.rb:52:in `fetch'
     # /builddir/build/BUILD/rubygem-i18n_data-0.4.0/usr/share/gems/gems/i18n_data-0.4.0/lib/i18n_data.rb:18:in `countries'
     # /builddir/build/BUILD/rubygem-i18n_data-0.4.0/usr/share/gems/gems/i18n_data-0.4.0/spec/i18n_data_spec.rb:122:in `block (6 levels) in <top (required)>'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:114:in `instance_eval'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:114:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example.rb:111:in `run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:390:in `block in run_examples'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `map'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:386:in `run_examples'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:371:in `run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `map'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `map'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `map'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/example_group.rb:372:in `run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/reporter.rb:34:in `report'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80:in `run'
     # /usr/share/gems/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:17:in `block in autorun'
```

Running ```LANG=en_US.utf8 rspec spec``` works just fine => external encoding for files should be defined in source code to work correctly no matter what system encoding is.

### PR DESCRIPTION
**Pull request by AgentAntelope**
This fixes #4

### CODE REVIEW

**Comment by AgentAntelope** [comment]
The reason this fails the tests is that ruby 1.8.7 doesn't support specifying the encoding of a string to be read with `.readlines`. I don't know of any 1.8.7 friendly way to solve this issue, as 1.9 was the first ruby release to handle encodings in this manner. Any ideas?

**Comment by grosser** [comment]
remove 1.8 support and declare `  s.required_ruby_version = '>= 1.9.3'`

**Comment by grosser** [comment]
most likely setting external_encoding correctly would also have fixed it, but it's a good patch either way

**Comment by AgentAntelope** [comment]
Awesome, thanks for the quick response :)

**Comment by grosser** [comment]
thx for the PR, 0.7.0 is out :)

**Pull request merged**
