### PR TITLE
Extract ISO data from iso-codes JSON

### PR DESCRIPTION
**Pull request by rwd**
Update LiveDataProvider to:
1. Use the new iso-codes Git repo URL https://salsa.debian.org/iso-codes-team/iso-codes.git
2. Extract language and country names from iso-codes' JSON data files that have replaced the XML data files

This does not yet update the file data cache which can happen in a follow-up PR if this one is merged.

### CODE REVIEW

**Comment by rwd** [comment]
Specs fail due to the upstream removal of the `mo` language.

**Comment by rwd** [comment]
Specs updated with a temporary workaround to reflect upstream removal of one language, until file data cache is updated.

**Comment by grosser** [comment]
amazing :D

**Comment by grosser** [comment]
can you send the PR for file-cache update, so the gem is in a consistent state ?

**Pull request merged**
